# -------------------------------- CUSTOM SITE VARIABLES --------------------------------
vars:
  conference:
    short_name: &short_name O-COCOSDA 2026
    full_name: 29th International Conference of Oriental COCOSDA
    dates: November 25-27, 2026
    short_location: Cebu, Philippines
    full_location: Plantation Bay Resort and Spa, Mactan Island, Cebu, Philippines
  important_dates:
    paper_submission: July 10, 2026
    acceptance_notif: August 10, 2026
    camera_ready: August 31, 2026
# -------------------------------- START OF THEME CONFIG --------------------------------

title: *short_name
description: The conference website for O-COCOSDA 2026, the 29th International Conference of Oriental COCOSDA.
theme: just-the-docs

url: https://ococosda2026.github.io/test

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/ococosda-logo.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/ococosda-favicon.ico"

# Footer content
# appears at the bottom of every page's main content
footer_content: "© 2026 <strong>O-COCOSDA 2026 Organizing Committee</strong>."

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
# uses ruby's time format: https://docs.ruby-lang.org/en/3.2/strftime_formatting_rdoc.html
last_edit_time_format: "%b %e %Y at %I:%M %p GMT+8" # Sample output: May 22 2026 at 02:45 PM GMT+8

# Color for callout
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red




# Ignore sass deprecation warnings
sass:
  quiet_deps: true # https://github.com/just-the-docs/just-the-docs/issues/1541
  silence_deprecations: ['import'] # https://github.com/just-the-docs/just-the-docs/issues/1607